# Generated by Django 4.1.5 on 2023-01-12 07:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=255)),
                ('auctionuser_buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('auctionuser_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_review_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
