# Generated by Django 4.1.5 on 2023-01-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auction",
            name="end_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="auction",
            name="start_date",
            field=models.DateTimeField(),
        ),
    ]
