# Generated by Django 4.1.5 on 2023-01-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='number_of_bids',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
