# Generated by Django 4.1.5 on 2023-01-07 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
