# Generated by Django 4.1.5 on 2023-01-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('SD', 'Delivered'), ('SS', 'Sold'), ('PN', 'Pending')], default='PN', max_length=2),
        ),
    ]
