# Generated by Django 4.1.5 on 2023-01-10 14:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='starting_price',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(1.0)]),
        ),
    ]
