# Generated by Django 4.1.5 on 2023-01-12 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0007_alter_product_starting_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_product_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
