# Generated by Django 4.1.5 on 2023-01-14 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_product_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="photo",
        ),
    ]
